### ISSUE TITLE
Consider using trestle as ORM

### ISSUE THREAD

**Issue by adaojunior** [lteacher/shellstone#21]
Hi, first of all, thank you for starting this package and helping the dart community.
I noticed that you're implementing a ORM as well, that's great, but I noticed that it is very similar with [trestle](https://pub.dartlang.org/packages/trestle), and I wonder if it would be better for the community if we could reuse some of the already existing packages, mostly to focus the work and have mature packages. Emil is really open to contributions, and I'm sure he will be glad to listen to your ideas and contributions.

**Comment by emilniklas** [comment]
Hello!

I'm the one that made Trestle. I had a few goals in mind when I started:
- A query DSL that would look like native Dart code, by parsing closures like `.where((u) => u.age > 18)` to actual SQL queries
- An ORM that was detached from the main query builder (so that you could use the query DSL without actually doing the whole model ceremony, and get simple maps back)
- Asynchrony with Streams and Futures as responses. (and no `Future<List>`)
- Connectors to different databases (MySQL and Postgres, as well as a native in-memory Dart implementation is available right now)
- Models should not have to be annotated, and schemas should be decided in Migrations
  - Because most people don't want their data layer to be coupled to a specific database library, plain Dart classes should be usable as models as well.

I'd be very open for collaborating on Trestle, and I think @adaojunior has a point in that the community would profit from reusing libraries.

**Comment by lteacher** [comment]
Hello,

Yes actually I did see the project admittedly after I had already started but I did come across it at some point and I also used some knowledge from the mysql driver regarding the generator for the stream output.

The thing is that I had already started and I am crunching on pretty heavily with this having been going for around 3 weeks. I did recently stop another project when I found that there was another thing that did just what I was planning and instead rather planned to contribute to that but when I saw the other ORM examples I didn't feel that they were really that similar to my plans.

In contrast to the above I am using  annotations very heavily, as mentioned part of the inspiration for that is the Redstone package which I was planning to integrate with in some way so I felt that annotated Routes, Interceptors, Models and so on made good sense. Then with that in mind I didnt wish to force the extension of some Model unless the user wants to mix in some features, hence why there is a manager of sorts dispatching the queries etc. 

I think the query language is very similar in ideas, i only want it to be pleasant to use with a native dart syntax and acceptable typings, if you [take a look at the tests you can see already](https://github.com/lessonteacher/shellstone/blob/master/test/mysql_adapter_test.dart#L17) what is there

**Comment by emilniklas** [comment]
@lessonteacher 

I am very familiar with wanting to make your own things instead of using others, even if that means reinventing the wheel in some places. However, I think that the best things are made when you collaborate on a problem.

I would not blame you if you just wanted to keep going on this (That's probably what I'd have done). But maybe, if you wanted to, you could take some of your ideas and code and join Trestle as a organization member. I particularly like the way you _actually_ lex the expressions and parse them — I like that more than my old solution: a bunch of regexes.

One final reason is that there are things to be gained in moving some of the DB stuff to its own project. It would clean up the repo for a more substantial web framework project.

In any case, good work and all! :)

**Comment by lteacher** [comment]
Ok well here is about where I am at.

I agree that its better to collaborate to achieve more. Maybe the best thing is for me to reply to the above points then since I dont want to just say _'nah im doing my own thing...'_ as that really is not very collaborative obviously, and I actually think the opposite.. but there are still reasons  why I am not contributing and instead building this currently, though mostly they relate to the fact that I had started after messing with Sails and had not seen the other project along with the fact that I wanted to create something open here.

To start off, per the main page, I have been basing a fair amount of my ideas off [Sails waterline](https://github.com/balderdashy/waterline) as I felt that it looks relatively pleasant, but obviously the js objects don't really coincide so instead the annotated approach felt like a natural choice. Any parts of my ideas so far that are similar to trestle would be coincidental and so perhaps even that shows that we do have like-minded visions of sorts.

> A query DSL that would look like native Dart code, by parsing closures like .where((u) => u.age > 18) to actual SQL queries

_I agree that this is good, per my previous comment and examples I wanted to see both; the ability to do this which both packages are doing now, I use the [filter()](https://github.com/lessonteacher/shellstone/blob/master/test/mysql_adapter_test.dart#L220)  method for that, but I also provide the full chain of query options to allow someone to [build a query](https://github.com/lessonteacher/shellstone/blob/master/test/mysql_adapter_test.dart#L172) up and the typing is defined so can be seen with the linter. I think this lines up the same._

> An ORM that was detached from the main query builder (so that you could use the query DSL without actually doing the whole model ceremony, and get simple maps back)

_I sort of agree with this one, I have planned in my roadmap (which is more like random points here and there... actually I forgot to put it anywhere it seems but involves changing the `update` etc to `updateFrom(Entity) vs update(name,Map values)`) to try and allow this at minimum for the modify related functions. Im not sure about the map results etc but I suppose someone would potentially want to get their `Stream<Map>` back instead of always `Stream<Entity>` so seems like a good feature, its just that its also similar to the native call that should be possible for all adapters / drivers anyway. E.g your `SqlDriver` does this and I think that is the appropriate way. I have a similar thought and in a rudimentary way allow someone to go `adapters('mysql').driver.then(dostuff)` which admittedly probably isn't enjoyable enough_

> Asynchrony with Streams and Futures as responses. (and no Future<List>)

_I agree, though I do produce a `Future<List<int>>` for results of insertions currently... However I plan to rewrite that thing and couldn't disagree with this it pretty much makes sense that if the result is a collection its a `Stream` and if its a single value its a `Future`_

> Connectors to different databases (MySQL and Postgres, as well as a native in-memory Dart implementation is available right now)

_I plan to connect up multiple databases, see the waterline stuff. Most importantly I want document storage dbs as well like mongodb. Obviously I can't say much about what is already working in trestle as my aims are not to compete with anything but just actually for my own enjoyment whilst hopefully producing something people can use. Since I am not part of the project and a relative Dart noob, when i started obviously I need to implement these so that is what i have been doing_

> Models should not have to be annotated, and schemas should be decided in Migrations

_For me the annotations are the schemas and possibly migrations though i have not gotten near considering that particular aspect as yet, at least that is my aim. The way I see it is that requesting the user to annotate their models is relatively unobtrusive and shows clear intent regarding the object that is annotated. Using the annotations, we can easily add relevant parameters for the schema etc without needing the user to deal with it. Probably the modelling part is one of the best use cases of them actually. I don't think they should be able to be opted out. Again per the waterline, with the annotation can actually choose the driver for them which allows them to say_

``` dart
@Model('Thing', source: 'mongo')...
@Model('OtherThing', source: 'mysql')
```

_Or whatever the most beautiful syntax is that is determined. If anything the `@Model` attribute is almost better as you could have some `@Model('Thing', schema:false)` (note this is not an original idea, its again from waterline, its not than I am a mega fan of waterline, just if it makes sense..) then automatically use the attributes so then the one single tag is the minimum This relates then directly to_

> Because most people don't want their data layer to be coupled to a specific database library, plain Dart classes should be usable as models as well

_Agreed as mentioned I also think that decoupling fro the database library is critical, per the above planned example which shows this as well. Regarding the last part, again of course I agree but dont agree that it should be possible randomly without making it clear. I think the user should clearly state the class is a model either via annotation or composition then opt in and out of various properties as fields or whatever again in some way and then it makes sense that annotations become the niceset way, the same as how you also are using them for fields when desired, so its now more consistent and clearer regarding intent._

So anyways, those are my comments. Regarding where I am at now, obviously I don't know your thoughts regarding my comments as I am now only writing them, but I will be continuing on this project at this stage unless there are changes, this is just because I am working on this daily and I don't want to lose momentum.

**Comment by lteacher** [comment]
I think it is time for me to close this one. I believe my aims are clear and I think I expressed my thoughts well above so there has been nothing further in regards to this issue. 

Thanks for raising this, however, as I think I got a lot out of thinking through this.
